### ISSUE TITLE
[FavoriteMedia]: Image list slow loading

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#153]
### Discord Build

Stable

### Discord Version

Stable 162224 (e1ec9ed)

### Plugin Version

v1.6.3

### Steps To Reproduce

Have a ton of images favorited in the plugin
open the favorite media gui
experience slow loading

### Describe the bug

Favorite media GUI takes a little too long to load, this is definetly that i have 70+  images saved but this only started happening for the past 3 days before which i alrd had around this number of images saved in a category, maybe i surprassed a specific number of images or smthn idk.

anyhow i know this is more of a limitation but i just hope there is a possible workaround for this, if this is just to keep the plugin optimized for low end devices perhaps make it so if discord's accelerated hardware option is enabled it has everything loaded alrd or smthn.

I apologize if this is post is a little to superflous

**Comment by Aezaeo** [comment]
I've suggested this before but I wonder if a possible workaround for this would be to add a pages type loading system. Like if you go to the images tab and there's 50 images, it would show 10 (or a set amount) images then to access the next images the user would choose page 2, etc. Much like how the search function works. I believe the search function loads 25 posts before the user has to change the page.
![9wKEGSf 1](https://user-images.githubusercontent.com/24560181/206015224-5b028dfb-a56c-4f6e-97e4-4c99a26266a2.png)




I'm assuming the issue with FavoriteMedia is because it attempts to load all images for scrolling until you've reached the end. So if a user has a lot of images then it gets stuck processing all the images to load within the tab for scrolling purposes.

**Comment by Dastan21** [comment]
It works the same way as how GIFs tab work. It loads only visible image, you can test by opening the image/video tab and looking at the images loading, then scroll a bit and the next images will load too: they were not already loaded.

**Comment by DeCat4** [comment]
the issue isn't the scrolling i think the issue is with the categories system, as i use it.

Is there a chance that when you don't have a category open alll the images are loaded so that it can display them as the thumbnail? because when the category is opened it doesn't spend time to laod the first images which it should.

**Comment by Dastan21** [comment]
It randomly choose a thumbnail link from the category list (in the .config.json [where the medias links are saved]) then creates the HTML element (<img>), so it won't load unecessary images/thumbails.

**Comment by DeCat4** [comment]
sorry for my slow answers, forget to check my notifs.


Huh, then idk what's going on but it takes way too long to load when i open up the tab, is there any chance you can see if there is a way to optimize this? maybe it loads the list of the links or somethin?

I only have 5 categories in total so it only loads 5 images realistically, either discord has some sort of limit of how much ram it can dedicate for certain features or there's something else loading that's messing things up

I apologize if i'm taking this a little to far i'm just confused as this never happened before discord broke btd

**Comment by Dastan21** [comment]
Should be better in 1.7.0, I have added medias preloading (before even opening media tabs.
