### ISSUE TITLE
[FavoriteMedia]: Too much saved media to refresh URLs

### ISSUE THREAD

**Issue by Halokiller990** [Dastan21/BDAddons#248]
### Discord Build

Stable

### Discord Version

Stable 288460 (c8280c6)

### Plugin Version

v1.9.0

### Steps To Reproduce

Have a large amount of favorited media. (In my case 2400+ images and 1200+ for videos.)

Refresh URLs

### Describe the bug

The URLs for images or videos never refresh because I believe I have too many favorited. I have 32 audio files favorited and the refresh URLs feature works fine there. 

Is it possible to make the URL refresh work for larger repositories of images? 

Alternatively, could there be an option to refresh URLs on a single page? This would be so that it doesn't time out from refreshing 1000+ media in one go.

### Screenshots
![image](https://github.com/Dastan21/BDAddons/assets/48164233/f00dbef8-c535-4534-aa9f-74504d63e2a5)

**Comment by DeCat4** [comment]
honestly we need a feature to just drop the files ourselves into a folder rather than relying on a URL.

**Comment by AlphaGaming7780** [comment]
I like the ID of refresh URL for one page, like if the URL is outdated the mod automatically refresh the URL for the outdated URL on this page, and if we change page they update the new one.
Also, saving the refreshed URL would be cool, because I have to refresh everything each time I close and start discord.

**Comment by Dastan21** [comment]
Fixed in v1.10.0.
Links are now only refreshed when needed (upload, download, cache...).
