### ISSUE TITLE
[FavoriteMedia]: Plugin causes crash whenever I open a channel 1.10.4

### ISSUE THREAD

**Issue by Fallen-Feces** [Dastan21/BDAddons#275]
### Discord Build

Stable

### Discord Version

341775 (b8e14e8)

### Plugin Version

1.10.4

### Steps To Reproduce

1. Open Discord
2. Open any channel
3. Discord dies

### Describe the bug

Looking at the console I'm seeing things like `TypeError: Cannot read properties of undefined (reading 'Messages')` or that same error but replace "Messages" with "exports". I saw a mention that this was caused by Zeres Library but after disabling that this still occurs.

**Comment by Dastan21** [comment]
Duplicate #274

**Comment by MahdeenSky** [comment]
any workaround? unusable atm

**Comment by Ryuktheshinigamix** [comment]
+1

**Comment by Infinitay** [comment]
@Fallen-Feces @MahdeenSky @Ryuktheshinigamix Pinging you all since I had the same issue, and I found out today that it was in fact fixed. For some reason my BetterDiscord wasn't auto-updating it, so I never knew that it fixed until I updated manually. I fixed it by updating to the current latest (1.11.0, but I guess it should be 1.11.1 but he forgot to change the version?) the issue went away for me. Replace your FavoriteMedia.plugin.js with the current latest version: https://raw.githubusercontent.com/Dastan21/BDAddons/refs/heads/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js

Try that out and see if it fixes for you too. I'm not sure if he implemented a workaround and Zeres is still broken or not, but I guess the following commit specifically fixed this specific issue https://github.com/Dastan21/BDAddons/commit/9bdb55b6baf56f6058e0b265f7f8e73d9ffefc7b

**Comment by Ryuktheshinigamix** [comment]
@Infinitay The most recent update, almost 20 hours ago at this point, has already fixed this issue for me. It also auto-updated just fine for me. It seems Zeres is also compatible again as well, though I've faced this issue without it as well. when I had the issue originally re-downloading it from the most recent release from github should always be a first and at that time It was still broken.
