### ISSUE TITLE
[FavoriteMedia]: crash upon load

### ISSUE THREAD

**Issue by canna-bidiol** [Dastan21/BDAddons#278]
### Discord Build

Stable

### Discord Version

stable 342968 (f8fde36) Host 1.0.9169 x64 (54876) Build Override: N/A Windows 11 64-bit (10.0.22631)

### Plugin Version

1.10.4

### Steps To Reproduce

1. Download FavoriteMedia
2. Install FavoriteMedia
3. Enable FavoriteMedia in settings
4. Exit settings
5. Open up any chat, it crashes

### Describe the bug

Upon the plugin needing to be loaded in/displayed, it immediately crashes discord. I've tried it without any other plugins or themes enabled, made sure all was up to date as well. Apologies if I put this in the wrong place, I don't use Github ever.

### Screenshots

![image](https://github.com/user-attachments/assets/0c4b7fea-7058-4af0-87e5-7a6d47673ee2)

**Comment by Infinitay** [comment]
@canna-bidiol I was facing the same issue as you, but I guess FavoriteMedia was in fact the problem because after I updated it to the current latest (1.11.0, but I guess it should be 1.11.1 but he forgot to change the version?) the issue went away for me. Replace your FavoriteMedia.plugin.js with the current latest version: https://raw.githubusercontent.com/Dastan21/BDAddons/refs/heads/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js

Try that out and see if it fixes for you too
